
import React, { useState } from 'react';
import { MediaItem } from '../types';
import { Image as ImageIcon, Film, Download, Trash2, Maximize2, RefreshCw } from 'lucide-react';

const MOCK_MEDIA: MediaItem[] = [
    { id: '1', type: 'image', url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop', prompt: 'A futuristic cyberpunk city with neon lights and flying cars', timestamp: '10:42 AM', model: 'gemini-3-pro-image-preview', metadata: { resolution: '1024x1024' } },
    { id: '2', type: 'image', url: 'https://images.unsplash.com/photo-1614726365723-49cfae968602?q=80&w=1000&auto=format&fit=crop', prompt: 'Abstract digital art representing neural networks', timestamp: '11:15 AM', model: 'imagen-3', metadata: { resolution: '1024x1024' } },
    { id: '3', type: 'video', url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', prompt: 'Time lapse of a flower blooming in a digital garden', timestamp: '11:30 AM', model: 'veo-3.1-generate-preview', metadata: { aspectRatio: '16:9' } },
    { id: '4', type: 'image', url: 'https://images.unsplash.com/photo-1535378437327-1017b2b246a3?q=80&w=1000&auto=format&fit=crop', prompt: 'High tech robot hand holding a glowing orb', timestamp: '12:05 PM', model: 'gemini-3-pro-image-preview', metadata: { resolution: '1024x1024' } },
];

const MediaGallery: React.FC = () => {
    const [items, setItems] = useState<MediaItem[]>(MOCK_MEDIA);
    const [filter, setFilter] = useState<'all' | 'image' | 'video'>('all');
    const [selectedItem, setSelectedItem] = useState<MediaItem | null>(null);

    const filteredItems = items.filter(i => filter === 'all' || i.type === filter);

    return (
        <div className="h-full flex flex-col space-y-6">
             <div className="flex justify-between items-center bg-slate-900/50 p-4 rounded-xl border border-slate-800">
                <div>
                    <h2 className="text-xl font-bold text-white flex items-center gap-2">
                        <ImageIcon className="text-violet-500" />
                        Generative Media Gallery
                    </h2>
                    <p className="text-sm text-slate-400">Manage assets generated by Gemini & Veo.</p>
                </div>
                <div className="flex bg-slate-950 p-1 rounded-lg border border-slate-800">
                    {['all', 'image', 'video'].map(f => (
                         <button
                            key={f}
                            onClick={() => setFilter(f as any)}
                            className={`px-4 py-1.5 text-xs font-bold uppercase rounded transition-all ${filter === f ? 'bg-slate-800 text-white shadow' : 'text-slate-500 hover:text-slate-300'}`}
                        >
                            {f}
                        </button>
                    ))}
                </div>
            </div>

            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 overflow-y-auto custom-scroll pr-2 pb-10">
                {filteredItems.map(item => (
                    <div key={item.id} className="group relative bg-slate-900 border border-slate-800 rounded-xl overflow-hidden hover:border-violet-500/50 transition-all shadow-lg hover:shadow-violet-500/10">
                         <div className="aspect-square bg-slate-950 flex items-center justify-center overflow-hidden">
                             {item.type === 'image' ? (
                                 <img src={item.url} alt={item.prompt} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                             ) : (
                                 <video src={item.url} className="w-full h-full object-cover opacity-80 group-hover:opacity-100" />
                             )}

                             {/* Overlay */}
                             <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2 backdrop-blur-sm">
                                 <button onClick={() => setSelectedItem(item)} className="p-2 bg-slate-800 rounded-full text-white hover:bg-violet-600 transition-colors" title="View">
                                     <Maximize2 size={18} />
                                 </button>
                                 <button className="p-2 bg-slate-800 rounded-full text-white hover:bg-emerald-600 transition-colors" title="Download">
                                     <Download size={18} />
                                 </button>
                                  <button className="p-2 bg-slate-800 rounded-full text-white hover:bg-blue-600 transition-colors" title="Regenerate Variation">
                                     <RefreshCw size={18} />
                                 </button>
                             </div>

                             <div className="absolute top-2 right-2 bg-black/50 px-2 py-1 rounded text-[10px] text-white font-mono backdrop-blur-md border border-white/10">
                                 {item.type === 'image' ? <ImageIcon size={12} /> : <Film size={12} />}
                             </div>
                         </div>
                         <div className="p-3">
                             <p className="text-xs text-slate-300 line-clamp-2 mb-2 leading-relaxed">"{item.prompt}"</p>
                             <div className="flex justify-between items-center text-[10px] text-slate-500 font-mono">
                                 <span>{item.model}</span>
                                 <span>{item.timestamp}</span>
                             </div>
                         </div>
                    </div>
                ))}
            </div>

            {/* Lightbox Modal */}
            {selectedItem && (
                <div className="fixed inset-0 z-50 bg-black/90 backdrop-blur-md flex items-center justify-center p-10 animate-in fade-in duration-200">
                    <div className="max-w-4xl w-full bg-slate-900 border border-slate-700 rounded-2xl overflow-hidden shadow-2xl flex flex-col max-h-full">
                        <div className="flex justify-between items-center p-4 border-b border-slate-800">
                             <h3 className="text-white font-bold flex items-center gap-2">
                                {selectedItem.type === 'image' ? <ImageIcon size={18} className="text-violet-500" /> : <Film size={18} className="text-violet-500" />}
                                Media Preview
                             </h3>
                             <button onClick={() => setSelectedItem(null)} className="text-slate-400 hover:text-white"><Trash2 size={20} /></button>
                        </div>
                        <div className="flex-1 bg-black flex items-center justify-center p-4 overflow-hidden">
                             {selectedItem.type === 'image' ? (
                                 <img src={selectedItem.url} alt={selectedItem.prompt} className="max-h-[60vh] object-contain rounded" />
                             ) : (
                                 <video src={selectedItem.url} controls className="max-h-[60vh] rounded" />
                             )}
                        </div>
                        <div className="p-6 bg-slate-900 border-t border-slate-800">
                            <p className="text-sm text-slate-300 font-mono mb-4 bg-slate-950 p-3 rounded border border-slate-800">{selectedItem.prompt}</p>
                            <div className="flex gap-4 text-xs text-slate-500 font-mono">
                                <span>Model: <span className="text-violet-400">{selectedItem.model}</span></span>
                                <span>Resolution: <span className="text-emerald-400">{selectedItem.metadata?.resolution || '720p'}</span></span>
                            </div>
                             <div className="mt-4 flex gap-3">
                                <button onClick={() => setSelectedItem(null)} className="flex-1 py-2 bg-slate-800 text-white rounded hover:bg-slate-700">Close</button>
                                <button className="flex-1 py-2 bg-violet-600 text-white rounded hover:bg-violet-500">Download Asset</button>
                             </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}

export default MediaGallery;
