import { NextRequest, NextResponse } from 'next/server';
import { ragChat, getSuggestedQuestions } from '@/lib/ai/ragChat';
import { getDocuments } from '@/lib/indexedDB';

export const runtime = 'nodejs';
export const maxDuration = 120; // 2 minutes

/**
 * RAG Chat API Endpoint
 * POST /api/rag-chat
 *
 * Body:
 * - query: string (user question)
 * - config: ModelConfig (AI provider configuration)
 * - history: ChatMessage[] (conversation history)
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { query, config, history = [] } = body;

    if (!query || typeof query !== 'string') {
      return NextResponse.json(
        { error: 'Query is required' },
        { status: 400 }
      );
    }

    if (!config) {
      return NextResponse.json(
        { error: 'Model configuration required' },
        { status: 400 }
      );
    }

    // Get documents from IndexedDB (server-side storage simulation)
    const documents = await getDocuments();

    console.log(`[RAG CHAT API] Processing query with ${documents.length} documents...`);

    const response = await ragChat(query, documents, history, config);

    console.log(`[RAG CHAT API] Response generated by ${response.provider}`);

    return NextResponse.json({
      success: true,
      response: response.response,
      provider: response.provider,
      references: response.references,
      hasContext: response.hasContext,
      contextDocs: response.contextDocs,
      suggestedQuestions: getSuggestedQuestions(documents)
    });

  } catch (error: any) {
    console.error('[RAG CHAT API] Error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error.message || 'Chat failed'
      },
      { status: 500 }
    );
  }
}
