import { NextRequest } from 'next/server';
import { withSecurity, securityConfig, createAPIResponse, createAPIError } from '@/lib/security';
import { autoAnalyzeRequestSchema, validateRequestBody, AutoAnalyzeRequest } from '@/lib/validation';

// Auto-analysis thresholds and rules
const ANALYSIS_THRESHOLDS = {
  temperature: {
    optimal: { min: 68, max: 78 }, // Fahrenheit
    warning: { min: 65, max: 82 },
    critical: { min: 60, max: 90 }
  },
  humidity: {
    optimal: { min: 40, max: 60 },
    warning: { min: 30, max: 70 },
    critical: { min: 20, max: 80 }
  },
  ph: {
    optimal: { min: 6.0, max: 7.0 },
    warning: { min: 5.8, max: 7.2 },
    critical: { min: 5.5, max: 7.5 }
  },
  soilMoisture: {
    optimal: { min: 40, max: 70 },
    warning: { min: 30, max: 80 },
    critical: { min: 20, max: 90 }
  },
  lightIntensity: {
    optimal: { min: 400, max: 800 }, // μmol
    warning: { min: 300, max: 1000 },
    critical: { min: 200, max: 1200 }
  },
  ec: {
    optimal: { min: 1.2, max: 2.4 }, // mS/cm
    warning: { min: 1.0, max: 2.8 },
    critical: { min: 0.8, max: 3.2 }
  }
};

export async function POST(request: NextRequest) {
  return withSecurity(request, async (req, context) => {
    try {
      // Validate and parse request body using enhanced validation
      const validatedData = validateRequestBody(autoAnalyzeRequestSchema, context?.validatedBody || {});
      const { sensorData, strain, growthStage, room, visualSymptoms } = validatedData as AutoAnalyzeRequest;

      // Additional validation for required sensor data
      if (!sensorData) {
        return createAPIError('Missing sensor data', 'MISSING_SENSOR_DATA', 400);
      }

    // Perform automatic analysis based on sensor data
    let analysis = performAutoAnalysis(sensorData, strain, growthStage);

    // If visual symptoms are provided, enhance the analysis
    if (visualSymptoms) {
      analysis = enhanceAnalysisWithVisualSymptoms(analysis, visualSymptoms, strain);
    }

      // Get recommendations based on current conditions
      const recommendations = generateRecommendations(analysis, sensorData, growthStage);

      return createAPIResponse({
        success: true,
        analysis: {
          ...analysis,
          autoGenerated: true,
          timestamp: new Date().toISOString(),
          room: room || 'Unknown'
        },
        recommendations,
        alerts: generateAlerts(analysis),
        timestamp: new Date().toISOString(),
        requestId: context?.clientIP || 'unknown'
      });

    } catch (error) {
      console.error('Auto-analysis error:', error);

      return createAPIError(
        'Failed to perform auto-analysis',
        'AUTO_ANALYSIS_ERROR',
        500,
        {
          details: error instanceof Error ? error.message : 'Unknown error',
          timestamp: new Date().toISOString(),
          requestId: context?.clientIP || 'unknown'
        }
      );
    }
  }, securityConfig.publicAPI);
}

function performAutoAnalysis(sensorData: any, strain?: string, growthStage?: string) {
  const { temperature, humidity, ph, soilMoisture, lightIntensity, ec } = sensorData;

  let healthScore = 100;
  let issues: string[] = [];
  let strengths: string[] = [];
  let diagnosis = 'Optimal Conditions';
  let confidence = 95;

  // Temperature analysis
  const tempF = temperature ? Math.round((temperature * 9/5) + 32) : null;
  if (tempF) {
    if (tempF < ANALYSIS_THRESHOLDS.temperature.critical.min || tempF > ANALYSIS_THRESHOLDS.temperature.critical.max) {
      healthScore -= 25;
      issues.push(`Critical temperature: ${tempF}°F`);
      diagnosis = 'Temperature Stress';
      confidence = 90;
    } else if (tempF < ANALYSIS_THRESHOLDS.temperature.warning.min || tempF > ANALYSIS_THRESHOLDS.temperature.warning.max) {
      healthScore -= 15;
      issues.push(`Suboptimal temperature: ${tempF}°F`);
      if (diagnosis === 'Optimal Conditions') diagnosis = 'Temperature Imbalance';
    } else {
      strengths.push(`Optimal temperature: ${tempF}°F`);
    }
  }

  // Humidity analysis
  if (humidity) {
    if (humidity < ANALYSIS_THRESHOLDS.humidity.critical.min || humidity > ANALYSIS_THRESHOLDS.humidity.critical.max) {
      healthScore -= 20;
      issues.push(`Critical humidity: ${humidity}%`);
      if (diagnosis === 'Optimal Conditions') diagnosis = 'Humidity Stress';
      confidence = 90;
    } else if (humidity < ANALYSIS_THRESHOLDS.humidity.warning.min || humidity > ANALYSIS_THRESHOLDS.humidity.warning.max) {
      healthScore -= 10;
      issues.push(`Suboptimal humidity: ${humidity}%`);
      if (diagnosis === 'Optimal Conditions') diagnosis = 'Humidity Imbalance';
    } else {
      strengths.push(`Optimal humidity: ${humidity}%`);
    }
  }

  // pH analysis
  if (ph) {
    if (ph < ANALYSIS_THRESHOLDS.ph.critical.min || ph > ANALYSIS_THRESHOLDS.ph.critical.max) {
      healthScore -= 30;
      issues.push(`Critical pH level: ${ph}`);
      diagnosis = 'pH Lockout';
      confidence = 95;
    } else if (ph < ANALYSIS_THRESHOLDS.ph.warning.min || ph > ANALYSIS_THRESHOLDS.ph.warning.max) {
      healthScore -= 15;
      issues.push(`Suboptimal pH: ${ph}`);
      if (diagnosis === 'Optimal Conditions') diagnosis = 'pH Imbalance';
    } else {
      strengths.push(`Optimal pH: ${ph}`);
    }
  }

  // Soil moisture analysis
  if (soilMoisture) {
    if (soilMoisture < ANALYSIS_THRESHOLDS.soilMoisture.critical.min || soilMoisture > ANALYSIS_THRESHOLDS.soilMoisture.critical.max) {
      healthScore -= 20;
      issues.push(`Critical soil moisture: ${soilMoisture}%`);
      if (diagnosis === 'Optimal Conditions') diagnosis = 'Water Stress';
      confidence = 90;
    } else if (soilMoisture < ANALYSIS_THRESHOLDS.soilMoisture.warning.min || soilMoisture > ANALYSIS_THRESHOLDS.soilMoisture.warning.max) {
      healthScore -= 10;
      issues.push(`Suboptimal soil moisture: ${soilMoisture}%`);
      if (diagnosis === 'Optimal Conditions') diagnosis = 'Moisture Imbalance';
    } else {
      strengths.push(`Optimal soil moisture: ${soilMoisture}%`);
    }
  }

  // Light intensity analysis
  if (lightIntensity) {
    if (lightIntensity < ANALYSIS_THRESHOLDS.lightIntensity.critical.min || lightIntensity > ANALYSIS_THRESHOLDS.lightIntensity.critical.max) {
      healthScore -= 15;
      issues.push(`Critical light intensity: ${lightIntensity} μmol`);
      if (diagnosis === 'Optimal Conditions') diagnosis = 'Light Stress';
      confidence = 85;
    } else if (lightIntensity < ANALYSIS_THRESHOLDS.lightIntensity.warning.min || lightIntensity > ANALYSIS_THRESHOLDS.lightIntensity.warning.max) {
      healthScore -= 8;
      issues.push(`Suboptimal light intensity: ${lightIntensity} μmol`);
      if (diagnosis === 'Optimal Conditions') diagnosis = 'Light Imbalance';
    } else {
      strengths.push(`Optimal light intensity: ${lightIntensity} μmol`);
    }
  }

  // EC analysis
  if (ec) {
    if (ec < ANALYSIS_THRESHOLDS.ec.critical.min || ec > ANALYSIS_THRESHOLDS.ec.critical.max) {
      healthScore -= 20;
      issues.push(`Critical EC level: ${ec} mS/cm`);
      if (diagnosis === 'Optimal Conditions') diagnosis = 'Nutrient Imbalance';
      confidence = 90;
    } else if (ec < ANALYSIS_THRESHOLDS.ec.warning.min || ec > ANALYSIS_THRESHOLDS.ec.warning.max) {
      healthScore -= 10;
      issues.push(`Suboptimal EC: ${ec} mS/cm`);
      if (diagnosis === 'Optimal Conditions') diagnosis = 'Nutrient Imbalance';
    } else {
      strengths.push(`Optimal EC: ${ec} mS/cm`);
    }
  }

  // Growth stage specific adjustments
  if (growthStage) {
    switch (growthStage.toLowerCase()) {
      case 'seedling':
        if (humidity && humidity > 70) {
          healthScore += 5;
          strengths.push('Ideal humidity for seedlings');
        }
        if (lightIntensity && lightIntensity < 300) {
          strengths.push('Appropriate light intensity for seedlings');
        }
        break;
      case 'vegetative':
        if (humidity && humidity >= 50 && humidity <= 60) {
          healthScore += 5;
          strengths.push('Ideal humidity for vegetative growth');
        }
        if (lightIntensity && lightIntensity >= 500 && lightIntensity <= 700) {
          healthScore += 5;
          strengths.push('Ideal light intensity for vegetative growth');
        }
        break;
      case 'flowering':
        if (humidity && humidity >= 40 && humidity <= 50) {
          healthScore += 5;
          strengths.push('Ideal humidity for flowering');
        }
        if (tempF && tempF >= 68 && tempF <= 75) {
          healthScore += 5;
          strengths.push('Ideal temperature for flowering');
        }
        break;
    }
  }

  // Determine overall status
  let status = 'healthy';
  if (healthScore < 60) {
    status = 'critical';
  } else if (healthScore < 80) {
    status = 'warning';
  } else if (healthScore < 90) {
    status = 'attention';
  }

  return {
    diagnosis,
    confidence,
    healthScore: Math.max(0, Math.min(100, healthScore)),
    status,
    issues,
    strengths,
    sensorValues: {
      temperature: tempF,
      humidity,
      ph,
      soilMoisture,
      lightIntensity,
      ec
    },
    isPurpleStrain: strain?.toLowerCase().includes('purple') || false,
    growthStage: growthStage || 'unknown',
    strain: strain || 'unknown'
  };
}

function generateRecommendations(analysis: any, sensorData: any, growthStage?: string) {
  const recommendations: string[] = [];
  const { issues, strengths, status } = analysis;

  if (status === 'critical') {
    recommendations.push('🚨 Immediate attention required - Multiple critical issues detected');
  }

  // Temperature recommendations
  const tempF = sensorData.temperature ? Math.round((sensorData.temperature * 9/5) + 32) : null;
  if (tempF) {
    if (tempF < 65) {
      recommendations.push(`🌡️ Increase temperature to 68-78°F. Consider heating or better insulation.`);
    } else if (tempF > 82) {
      recommendations.push(`🌡️ Reduce temperature to 68-78°F. Improve ventilation or add cooling.`);
    }
  }

  // Humidity recommendations
  if (sensorData.humidity) {
    if (sensorData.humidity < 30) {
      recommendations.push(`💧 Increase humidity to 40-60%. Add humidifiers or mist plants.`);
    } else if (sensorData.humidity > 70) {
      recommendations.push(`💧 Reduce humidity to 40-60%. Improve air circulation and ventilation.`);
    }
  }

  // pH recommendations
  if (sensorData.ph) {
    if (sensorData.ph < 5.8) {
      recommendations.push(`⚗️ Raise pH to 6.0-7.0. Add pH up solution and flush if needed.`);
    } else if (sensorData.ph > 7.2) {
      recommendations.push(`⚗️ Lower pH to 6.0-7.0. Add pH down solution and flush if needed.`);
    }
  }

  // Soil moisture recommendations
  if (sensorData.soilMoisture) {
    if (sensorData.soilMoisture < 30) {
      recommendations.push(`💦 Water plants soon. Soil moisture is critically low.`);
    } else if (sensorData.soilMoisture > 80) {
      recommendations.push(`💦 Stop watering. Risk of root rot due to overwatering.`);
    }
  }

  // Light recommendations
  if (sensorData.lightIntensity) {
    if (sensorData.lightIntensity < 300) {
      recommendations.push(`💡 Increase light intensity to 400-800 μmol. Move lights closer or add more.`);
    } else if (sensorData.lightIntensity > 1000) {
      recommendations.push(`💡 Reduce light intensity to prevent light burn. Move lights further away.`);
    }
  }

  // EC recommendations
  if (sensorData.ec) {
    if (sensorData.ec < 1.0) {
      recommendations.push(`🧪 Increase nutrient concentration. EC is too low for healthy growth.`);
    } else if (sensorData.ec > 2.8) {
      recommendations.push(`🧪 Decrease nutrient concentration. Risk of nutrient burn.`);
    }
  }

  // Growth stage specific recommendations
  if (growthStage) {
    switch (growthStage.toLowerCase()) {
      case 'seedling':
        recommendations.push('🌱 Maintain high humidity (60-70%) and moderate light for seedlings.');
        break;
      case 'vegetative':
        recommendations.push('🌿 Focus on nitrogen-rich nutrients and 18+ hours of light during vegetative stage.');
        break;
      case 'flowering':
        recommendations.push('🌸 Switch to bloom nutrients and 12/12 light schedule for flowering.');
        break;
    }
  }

  // General maintenance recommendations
  if (issues.length === 0) {
    recommendations.push('✅ All parameters look good! Continue monitoring and maintain current conditions.');
  }

  recommendations.push('📊 Continue regular monitoring of all environmental parameters.');
  recommendations.push('🔧 Check equipment regularly to ensure consistent performance.');

  return recommendations;
}

function generateAlerts(analysis: any) {
  const alerts: any[] = [];
  const { status, issues, healthScore } = analysis;

  if (status === 'critical') {
    alerts.push({
      type: 'critical',
      title: 'Critical Issues Detected',
      message: `Health score: ${healthScore}/100. Immediate action required!`,
      timestamp: new Date().toISOString()
    });
  } else if (status === 'warning') {
    alerts.push({
      type: 'warning',
      title: 'Suboptimal Conditions',
      message: `Health score: ${healthScore}/100. Some parameters need attention.`,
      timestamp: new Date().toISOString()
    });
  }

  // Add specific issue alerts
  issues.forEach((issue: string) => {
    if (issue.includes('Critical')) {
      alerts.push({
        type: 'critical',
        title: 'Critical Alert',
        message: issue,
        timestamp: new Date().toISOString()
      });
    }
  });

  return alerts;
}

function enhanceAnalysisWithVisualSymptoms(analysis: any, visualSymptoms: string, strain?: string) {
  const symptoms = visualSymptoms.toLowerCase();
  const isPurpleStrain = strain?.toLowerCase().includes('purple') || false;

  // Enhanced purple symptom detection for visual analysis
  const hasSicknessSymptoms = symptoms.includes('yellow') || symptoms.includes('yellowing') ||
                               symptoms.includes('curl') || symptoms.includes('curling') ||
                               symptoms.includes('wilting') || symptoms.includes('spot') ||
                               symptoms.includes('brown') || symptoms.includes('rust') ||
                               symptoms.includes('necrosis') || symptoms.includes('dry') ||
                               symptoms.includes('crispy') || symptoms.includes('weak') ||
                               symptoms.includes('discolor') || symptoms.includes('pale');

  if (symptoms.includes('purple')) {
    // CRITICAL: Purple leaves + any other symptoms = DEFICIENCY (even in purple strains)
    if (hasSicknessSymptoms || symptoms.includes('leaf')) {
      analysis.healthScore = Math.min(analysis.healthScore - 30, 40);
      analysis.status = 'critical';
      analysis.issues.push('CRITICAL: Purple discoloration on leaves indicates phosphorus deficiency');
      analysis.diagnosis = 'Phosphorus Deficiency with Visual Symptoms';
      analysis.confidence = 95;

      // Add detailed explanation
      analysis.issues.push('Purple leaf coloration is NOT normal - indicates severe nutrient deficiency');
      analysis.issues.push('This requires immediate treatment with phosphorus-rich nutrients');

      return analysis;
    }
    // Purple on non-purple strain = DEFICIENCY
    else if (!isPurpleStrain) {
      analysis.healthScore = Math.min(analysis.healthScore - 20, 60);
      analysis.status = analysis.status === 'healthy' ? 'warning' : analysis.status;
      analysis.issues.push('Purple discoloration on non-purple strain indicates phosphorus deficiency');
      analysis.diagnosis = 'Phosphorus Deficiency';
      analysis.confidence = 90;

      return analysis;
    }
    // Purple on purple strain with NO other symptoms = LIKELY GENETIC (but still monitor)
    else if (isPurpleStrain && !hasSicknessSymptoms) {
      analysis.strengths.push('Purple coloration consistent with genetic strain characteristics');
      // Still reduce health score slightly for monitoring
      analysis.healthScore = Math.max(analysis.healthScore - 5, 80);

      return analysis;
    }
  }

  // Handle other critical visual symptoms
  if (symptoms.includes('yellow') || symptoms.includes('yellowing')) {
    analysis.healthScore = Math.min(analysis.healthScore - 25, 55);
    analysis.status = 'warning';
    analysis.issues.push('Yellowing indicates nutrient imbalance');
  }

  if (symptoms.includes('curl') || symptoms.includes('wilting')) {
    analysis.healthScore = Math.min(analysis.healthScore - 20, 60);
    analysis.status = analysis.status === 'healthy' ? 'attention' : analysis.status;
    analysis.issues.push('Leaf curling/wilting indicates environmental stress');
  }

  if (symptoms.includes('spot') || symptoms.includes('brown') || symptoms.includes('rust')) {
    analysis.healthScore = Math.min(analysis.healthScore - 15, 65);
    analysis.issues.push('Leaf spots indicate calcium/magnesium deficiency or disease');
  }

  return analysis;
}

// GET endpoint for current analysis status
export async function GET(request: NextRequest) {
  return withSecurity(request, async (req, context) => {
    const { searchParams } = new URL(request.url);
    const room = searchParams.get('room');

    return createAPIResponse({
      success: true,
      message: 'Auto-analysis service is running',
      supportedEndpoints: {
        autoAnalysis: '/api/auto-analyze',
        realTimeMonitoring: true,
        continuousAnalysis: true,
        visualSymptoms: true,
        sensorDataAnalysis: true
      },
      room: room || 'all',
      requestId: context?.clientIP || 'unknown'
    });
  }, securityConfig.publicAPI);
}